import type { AgentHintEntry } from './agent-hints.types';
import { GENERATED_HINTS } from './agent-hints.manifest.generated';
import { VIRTUAL_HINTS, PENDING_DIRECTIVES } from './agent-hints.manifest.base';

/**
 * Final manifest seen by `AgentHintRegistry`. Merges three sources:
 *  - `GENERATED_HINTS` (AST-derived, regenerated by `npm run hints:build`)
 *  - `VIRTUAL_HINTS` (class-level / programmatic paths with no DOM node)
 *  - `PENDING_DIRECTIVES` (Phase 0 backlog — paths declared but no
 *    `appAgentHint` directive added to the template yet)
 *
 * Duplicate paths across sources log a console.warn at module load and
 * the first source wins (generated > virtual > pending). Intermediate
 * containers missing from all sources are auto-filled with `activatable:
 * false` so the tree walk has a node at every depth.
 *
 * Descriptions live in i18n dictionaries under `agentHint.<dotted-path>`
 * (or `agentHint.<dotted-path>.self` for container entries that also
 * have children). The registry resolves them via `I18nService` at query
 * time so locale changes take effect immediately.
 */
export const AGENT_HINTS_MANIFEST: AgentHintEntry[] = mergeManifest();

function mergeManifest(): AgentHintEntry[] {
  const records = new Map<string, boolean>();
  const conflicts: string[] = [];

  function ingestTree(entries: AgentHintEntry[], parent: string): void {
    for (const e of entries) {
      const p = parent ? `${parent}/${e.id}` : e.id;
      if (records.has(p)) {
        conflicts.push(p);
      } else {
        records.set(p, !!e.activatable);
      }
      if (e.children) ingestTree(e.children, p);
    }
  }

  ingestTree(GENERATED_HINTS, '');
  ingestTree(VIRTUAL_HINTS, '');
  for (const pd of PENDING_DIRECTIVES) {
    if (records.has(pd.path)) {
      conflicts.push(pd.path);
    } else {
      records.set(pd.path, !!pd.activatable);
    }
  }

  if (conflicts.length) {
    console.warn('[agent-hints] duplicate manifest paths (first source wins):', conflicts);
  }

  for (const path of [...records.keys()]) {
    const segs = path.split('/');
    for (let i = 1; i < segs.length; i++) {
      const ancestor = segs.slice(0, i).join('/');
      if (!records.has(ancestor)) records.set(ancestor, false);
    }
  }

  interface Node { id: string; activatable: boolean; children: Map<string, Node> }
  const roots = new Map<string, Node>();
  for (const path of [...records.keys()].sort()) {
    const segs = path.split('/');
    let level = roots;
    let node: Node | undefined;
    for (const seg of segs) {
      node = level.get(seg);
      if (!node) {
        node = { id: seg, activatable: false, children: new Map() };
        level.set(seg, node);
      }
      level = node.children;
    }
    if (node) node.activatable = !!records.get(path);
  }

  function toEntries(nodes: Iterable<Node>): AgentHintEntry[] {
    return [...nodes].map((n) => {
      const out: AgentHintEntry = { id: n.id };
      if (n.activatable) out.activatable = true;
      if (n.children.size) out.children = toEntries(n.children.values());
      return out;
    });
  }
  return toEntries(roots.values());
}
