import type { AgentHintEntry, AgentHintPathDecl } from './agent-hints.types';
import { GENERATED_HINTS } from './agent-hints.manifest.generated';
import { VIRTUAL_HINTS, PENDING_DIRECTIVES } from './agent-hints.manifest.base';

/**
 * Final manifest seen by `AgentHintRegistry`. Merges three sources:
 *  - `GENERATED_HINTS` (AST-derived, regenerated by `npm run hints:build`)
 *  - `VIRTUAL_HINTS` (class-level / programmatic paths with no DOM node)
 *  - `PENDING_DIRECTIVES` (Phase 0 backlog — paths declared but no
 *    `appAgentHint` directive added to the template yet)
 *
 * All three are flattened to `(path, activatable)` records, intermediate
 * containers auto-filled with `activatable: false`, then re-shaped into
 * the nested `AgentHintEntry[]` tree. Duplicate paths with conflicting
 * activatable flags log a console.warn at module load.
 *
 * Descriptions live in i18n dictionaries under `agentHint.<dotted-path>`
 * (or `agentHint.<dotted-path>.self` for container entries). The registry
 * resolves them via `I18nService` at query time so locale changes take
 * effect immediately.
 */
export const AGENT_HINTS_MANIFEST: AgentHintEntry[] = mergeManifest();

function mergeManifest(): AgentHintEntry[] {
  const records = new Map<string, boolean>();
  const conflicts: string[] = [];

  function record(path: string, activatable: boolean): void {
    const existing = records.get(path);
    if (existing !== undefined) {
      if (existing !== activatable) conflicts.push(path);
      return;
    }
    records.set(path, activatable);
  }

  function flattenTree(entries: AgentHintEntry[], parent: string): void {
    for (const e of entries) {
      const p = parent ? `${parent}/${e.id}` : e.id;
      record(p, !!e.activatable);
      if (e.children) flattenTree(e.children, p);
    }
  }

  function flattenFlat(decls: readonly AgentHintPathDecl[]): void {
    for (const d of decls) record(d.path, !!d.activatable);
  }

  flattenFlat(GENERATED_HINTS);
  flattenTree(VIRTUAL_HINTS, '');
  flattenFlat(PENDING_DIRECTIVES);

  if (conflicts.length) {
    console.warn('[agent-hints] activatable flag conflicts across manifest sources:', conflicts);
  }

  for (const path of [...records.keys()]) {
    const segs = path.split('/');
    for (let i = 1; i < segs.length; i++) {
      const ancestor = segs.slice(0, i).join('/');
      if (!records.has(ancestor)) records.set(ancestor, false);
    }
  }

  interface Node { id: string; activatable: boolean; children: Map<string, Node> }
  const roots = new Map<string, Node>();
  for (const path of [...records.keys()].sort()) {
    const segs = path.split('/');
    let level = roots;
    let node: Node | undefined;
    for (const seg of segs) {
      node = level.get(seg);
      if (!node) {
        node = { id: seg, activatable: false, children: new Map() };
        level.set(seg, node);
      }
      level = node.children;
    }
    if (node) node.activatable = !!records.get(path);
  }

  function toEntries(nodes: Iterable<Node>): AgentHintEntry[] {
    return [...nodes].map((n) => {
      const out: AgentHintEntry = { id: n.id };
      if (n.activatable) out.activatable = true;
      if (n.children.size) out.children = toEntries(n.children.values());
      return out;
    });
  }
  return toEntries(roots.values());
}
