// AUTO-GENERATED by tools/build-hints.ts — DO NOT EDIT.
// Run `npm run hints:build` to regenerate after touching templates.

import type { AgentHintEntry } from './agent-hints.types';

export const GENERATED_HINTS: AgentHintEntry[] = [
  {
    id: 'chat-input',
    children: [
    { id: 'agent-panel', activatable: true },
    { id: 'batch-replace', activatable: true },
    { id: 'cancel-edit' },
    {
      id: 'chat-config',
      activatable: true,
      children: [
      { id: 'cloud-pull' },
      { id: 'cloud-push' },
      {
        id: 'profile-manage-menu',
        activatable: true,
        children: [
        { id: 'change-disk-folder', activatable: true },
        { id: 'disk-sync-pull' },
        { id: 'disk-sync-push' },
        { id: 'profile-clone' },
        { id: 'profile-delete' },
        { id: 'profile-export' },
        { id: 'profile-import' },
        { id: 'profile-rename' },
      ],
      },
      { id: 'save-all' },
      { id: 'save-current' },
    ],
    },
    { id: 'engine-mode-toggle' },
    { id: 'export-story' },
    { id: 'ideal-outcome-toggle', activatable: true },
    { id: 'preview-payload', activatable: true },
    { id: 'prompt-profile', activatable: true },
    { id: 'save' },
    { id: 'send' },
    { id: 'stop' },
    { id: 'view-turn-updates', activatable: true },
  ],
  },
  {
    id: 'sidebar',
    children: [
    { id: 'adventure-books', activatable: true },
    { id: 'close-sidebar', activatable: true },
    { id: 'cost-prediction-toggle', activatable: true },
    {
      id: 'files-tab',
      activatable: true,
      children: [
      {
        id: 'file-sync',
        children: [
        { id: 'change-folder', activatable: true },
        { id: 'select-folder', activatable: true },
      ],
      },
      { id: 'token-char-switch', activatable: true },
    ],
    },
    { id: 'provider-selector' },
    {
      id: 'session-tab',
      activatable: true,
      children: [
      {
        id: 'start-session',
        activatable: true,
        children: [
        { id: 'tab-generate', activatable: true },
        { id: 'tab-prebuild', activatable: true },
      ],
      },
    ],
    },
    { id: 'settings', activatable: true },
    { id: 'sync-provider', activatable: true },
  ],
  },
];
